### ISSUE TITLE
Problemas con yarn y node

### ISSUE THREAD

**Issue by Jaluco** [IIC2513-2018-2/wican#1]
Hola, estoy usando ubuntu y cuando trato de hacer yarn install me sale el siguiente error:

The engine "node" is incompatible with this module. Expected version "^10.9.0".
Lo he intentado todo pero no hay caso, ayuda por favor.

**Comment by vixolo** [comment]
Lo curioso es que en la [wiki](https://github.com/IIC2513-2018-2/syllabus/wiki/Node.js) aparece que tenemos que usar Node.js versión `8.4.x`, pero en el `package.json` tenemos 

`  "engines": {
    "node": "^10.9.0", ...}`

 @raulmt qué versión de node debiéramos usar?

**Comment by raulmt** [comment]
Sí, esa es la respuesta correcta. Este semestre actualicé la versión de node en el template pero me olvidé que en al wiki estaba la versión anterior. Ya actualicé la wiki para que mencione la 10.9. Lamento la confusión
